### ISSUE TITLE
Not working with latest Chromium version 60

### ISSUE THREAD

**Issue by Chris-D2GO** [andrewspode/ohnoyoudidnt#2]
Google might have changed their API again. I tested this over the weekend with the latest Chromium version, 60, from the stretch RPI OS.  I got the "Aww snap". I'm still testing, but you may want to see if this works anymore. 

Thanks.

**Comment by Chris-D2GO** [comment]
I figured out my testing was flawed. I'm retesting over the next few days. It would be great if this could write out to a simple log file to see when it was used.

**Comment by andrewspode** [comment]
I just tested it and it appears to be working. I left the snippet I use for testing as a code comment in the source. This basically just eats up all the memory until it causes it to crash.

`var memoryEater = "nom"; while(true) {memoryEater = memoryEater += "nom";}`

This executes what is essentially a no-op on each tab to check if it gets a response. If there is a security reason why we can't execute (some Google pages IIRC) it can't track it.

If you can come up with some tests that *don't* trigger it - please do let me know.

As far as logging - not a bad call, but I'm not really actively developing this at the moment. Feel free to contribute. If you view the background process (from the extensions tab) it does show the console.logs if a tab is reloaded.
