### ISSUE TITLE
Crash detected, but no restart

### ISSUE THREAD

**Issue by scottsandersdev** [andrewspode/ohnoyoudidnt#4]
Hello! 

My colleagues and I have been using this plugin while we try to fix a memory leak in an application. We've each individually noticed that sometimes the tab is not restarted when it crashes. Just today it happened again, so I checked the background console logs and noticed that it was continually logging "Crashed .." but then not restarting. I moved this line 

```
chrome.tabs.reload(thisTab.id); 
```
Out of the if statement `if (tabSuccessCount[thisTab.id] > 0) {` and the page refreshed every time it crashed. 

I noticed you have a comment 

> I'm not sure if this is needed anymore, but it's not a bad check to do

So perhaps it wouldn't hurt to remove the if statement entirely? If not, I can do it locally with my own extension, but seems like this may be a problem that effects others as well.

**Comment by andrewspode** [comment]
Hi!

It's open source - do you want to do a PR?

Andrew

**Comment by scottsandersdev** [comment]
Done! - #5

**Comment by andrewspode** [comment]
Scott - thanks for the PR. I've merged and bumped the version to 1.0.4. I've updated the Chrome Store entry with the new code and it's being processed by Google (says it could take 60 minutes). Let me know if you don't see the new version come through next week!
